import { type NextPage } from "next";
import Head from "next/head";
import Button from "~/components/Button";
import { useAuth0 } from "@auth0/auth0-react";
import Link from "next/link";
import { useAuth } from "~/AuthContext";
import { env } from "~/env.mjs";

const Home: NextPage = () => {
  const { logout, loginWithRedirect } = useAuth0();

  const { user: data } = useAuth();

  return (
    <>
      <Head>
        <title>leaderboards.online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center gap-8 bg-almostBlack text-center tracking-tighter text-almostWhite`}
      >
        <div>
          <h1 className="text-2xl font-heading sm:text-7xl md:text-9xl">
            leaderboards{" "}
            <span className="ml-[-30px] stroke-white p-0 tracking-tighter text-purple-500">
              .online
            </span>
          </h1>
          <p className="text-md text-lightGray sm:text-lg">
            setup beautiful leaderboards{" "}
            <mark className="bg-purple-400">fast</mark>, comes with rich api
            support to easily plug into your apps
          </p>
        </div>
        {data === undefined ? (
          <h1>Loading....</h1>
        ) : data === null ? (
          <Button
            onClick={() => {
              loginWithRedirect({
                authorizationParams: {
                  audience: env.NEXT_PUBLIC_AUDIENCE,
                },
              })
                .then(console.log)
                .catch((e: Error) => {
                  console.log({ e });
                });
            }}
          >
            {"Let's Go >"}
          </Button>
        ) : (
          <div className="flex gap-4">
            <Button>
              <Link href={"/dashboard"}>dashboard</Link>
            </Button>
            <Button
              onClick={() => {
                logout();
              }}
            >
              Logout
            </Button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
