import { type NextPage } from "next";
import Head from "next/head";
import Button from "~/components/Button";
import { useAuth0 } from "@auth0/auth0-react";

const Home: NextPage = () => {
  const { isAuthenticated, loginWithRedirect, isLoading, logout } = useAuth0();
  return (
    <>
      <Head>
        <title>leaderboards</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center gap-8 bg-almostBlack text-center text-almostWhite`}
      >
        <div>
          <h1 className="text-2xl font-heading sm:text-7xl">leaderboards</h1>
          <p className="text-md text-lightGray sm:text-lg">
            setup beautiful leaderboards <mark>fast</mark>, comes with rich api
            support to easily plug into your apps
          </p>
        </div>
        {isLoading ? (
          <h1>Loading....</h1>
        ) : isAuthenticated ? (
          <Button
            onClick={() => {
              logout();
            }}
          >
            Logout
          </Button>
        ) : (
          <Button
            onClick={() => {
              loginWithRedirect({
                authorizationParams: {
                  audience: "https://api.leaderboards.land",
                },
              })
                .then(console.log)
                .catch((e: Error) => {
                  console.log({ e });
                });
            }}
          >
            {"Let's Go >"}
          </Button>
        )}
      </main>
    </>
  );
};

export default Home;
